### ISSUE TITLE
HLS-VI paper

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/hls-project#37] opened 2024-09-13 18:34 UTC
### Description
HLS-VI journal paper

### Acceptance Criteria
- [ ] Analyze the spatial consistency of VI
- [ ] Analyze the temporal consistency of VI
- [ ] Draft initial paper
- [ ] Sent the draft paper to co-authors for review and reconcile comments
- [ ] Sent the paper to journal for review and reconcile comments
- [ ] Publish paper

**Comment by madhuksridhar** [comment] 2024-10-03 13:11
@bwbaker1 Is this a duplicate of Qiang's paper? If so can we link his ticket and close this?

**Closed** 2024-10-08 14:16 UTC
